version: 0.2

phases:
  build:
    commands:
     - cd build_helpers
     - ./install_ta-lib.sh ${HOME}/dependencies/
     - cd ..
     - python -m pip install --upgrade pip wheel
     - export LD_LIBRARY_PATH=${HOME}/dependencies/lib:$LD_LIBRARY_PATH
     - export TA_LIBRARY_PATH=${HOME}/dependencies/lib
     - export TA_INCLUDE_PATH=${HOME}/dependencies/include
     - pip install -r requirements-dev.txt
     - pip install -e .
